name: Generate Firewall Checklist

on: [push]

jobs:
  generate-firewall-checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Go 1.19.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
        
    - name: Generate firewall checklist
      run: |
        go build -o firewall-checklist github.com/interstellartech/golang-doc-checker --p=$ANSIBLE-DIR

    - name: Run firewall checklist
      env:
        ANSIBLE_DIR: ${{ github.workspace }}/ansible
        OUTPUT_DIR: ${{ github.workspace }}/ansible/firewall-checklist
      run: |
        ./firewall-checklist --p=$ANSIBLE_DIR
  
    - name: Commit generated firewall checklist
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add $OUTPUT_DIR
        git commit -m "Add generated firewall checklist" || echo "No changes to commit"
